Vagrant.configure("2") do |config|
  # Using a lightweight, generic Ubuntu 22.04 box
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # SSH is enabled by default in this box
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
end
